fixtures:
  repositories:
    "stdlib": "https://github.com/puppetlabs/puppetlabs-stdlib"
    "translate": "https://github.com/puppetlabs/puppetlabs-translate"
    "cron_core": "https://github.com/puppetlabs/puppetlabs-cron_core.git"
  symlinks:
    "mysql": "#{source_dir}"
