fixtures:
  repositories:
    "stdlib": "https://github.com/puppetlabs/puppetlabs-stdlib"
    "archive": "https://github.com/voxpupuli/puppet-archive"
    "translate": "https://github.com/puppetlabs/puppetlabs-translate"
  symlinks:
    "mysql": "#{source_dir}"
