---
spec/spec_helper.rb:
  spec_overrides:
  - require 'spec_helper_local'
  coverage_report: true
  minimum_code_coverage_percentage: 69

.github/workflows/ci.yml:
  unmanaged: true
.github/workflows/nightly.yml:
  unmanaged: true
.github/workflows/release_prep.yml:
  unmanaged: true
.github/workflows/release.yml:
  unmanaged: true

Rakefile:
  changelog_since_tag: 'v11.0.3'
  changelog_max_issues: 500
  extra_disabled_lint_checks:
    - anchor_resource
    - params_empty_string_assignment
