---
appveyor.yml:
  delete: true
spec/spec_helper.rb:
  allow_deprecations: true
.travis.yml:
  extras:
  - rvm: 2.1.9
    script: bundle exec rake rubocop
.rubocop.yml:
  unmanaged: true
.rubocop_todo.yml:
  unmanaged: true
