---
.rubocop.yml:
  include_todos: true


spec/spec_helper.rb:
  spec_overrides:
  - require 'spec_helper_local'
  coverage_report: true

.github/workflows/ci.yml:
  unmanaged: true
.github/workflows/nightly.yml:
  unmanaged: false
.github/workflows/release_prep.yml:
  unmanaged: false
.github/workflows/release.yml:
  unmanaged: false

Rakefile:
  changelog_since_tag: 'v11.0.3'
  changelog_max_issues: 500
  extra_disabled_lint_checks:
    - anchor_resource
    - params_empty_string_assignment
