name 'puppetlabs-mysql'
version '0.0.1'
source 'git://github.com/puppetlabs/puppetlabs-mysql.git'
author 'PuppetLabs'
license 'Apache'
summary 'Mysql module'
description 'Mysql module'
project_page 'http://github.com/puppetlabs/puppetlabs-mysql'

dependency 'puppetlasb/create_resources', '>= 1.2.0'
