name 'puppetlabs-mysql'
version '0.2.0'
source 'git://github.com/puppetlabs/puppetlabs-mysql.git'
author 'Puppet Labs'
license 'Apache'
summary 'Mysql module'
description 'Mysql module'
project_page 'http://github.com/puppetlabs/puppetlabs-mysql'
# dependency 'puppetlabs/create_resources', '>= 1.2.0'
