name: Labeller

on:
  issues:
    types:
      - opened
      - labeled
      - unlabeled
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled

jobs:
  label:
    if: contains(fromJson('["puppetlabs", "puppet-toy-chest"]'), github.repository_owner)
    uses: "puppetlabs/cat-github-actions/.github/workflows/labeller.yml@main"
    secrets: inherit
